import {Button} from "std-widgets.slint";
import {Counter} from "counter.slint";
import {TodoItem} from "todo_item.slint";

export struct OneInt {
    value: int,
}

export struct ModelImpurity {
    foo: int,
}

export global Globals := {
    pure callback initialize_model() -> ModelImpurity;
    pure callback make_model(ModelImpurity) -> [OneInt];
}

export component UiMain inherits Window {
    VerticalLayout {
        text := Text {
            text: "hello world";
        }
        Button {
            text: "debug";
            preferred-width: 100px;
            preferred-height: 50px;

            clicked => {
                text.color = #ff0000;
            }
        }
        property<ModelImpurity> impurity: Globals.initialize_model();
        for val in Globals.make_model(self.impurity): Counter {
            value: val.value;
        }

        TodoItem {
            done: true;
            text: "kekus kekus kekus kekus kekus kekus kekus kekus kekus kekus kekus ";
        }
    }
}

