import {Button} from "std-widgets.slint";

export struct OneInt {
    value: int,
}

export struct ModelImpurity {
    foo: int,
}

export global Globals := {
    pure callback initialize_model() -> ModelImpurity;
    pure callback make_model(ModelImpurity) -> [OneInt];
}

component Counter {
    in-out property <int> value: 0;
    HorizontalLayout {

        Button {
            text: "-";
            max-width: self.height;
            clicked => { root.value -= 1; }
        }
        Rectangle {
            Text {
                text: root.value;
            }
        }
        Button {
            text: "+";
            max-width: self.height;
            clicked => { root.value += 1; }
        }
    }
}

export component UiMain inherits Window {
    VerticalLayout {
        text := Text {
            text: "hello world";
        }
        Button {
            text: "debug";
            preferred-width: 100px;
            preferred-height: 50px;

            clicked => {
                text.color = #ff0000;
            }
        }
        property<ModelImpurity> impurity: Globals.initialize_model();
        for val in Globals.make_model(self.impurity): Counter {
            value: val.value;
        }
    }
}

