import {CheckBox, Button, LineEdit} from "std-widgets.slint";

component EditableLabel inherits Rectangle {
    in property <bool> editable;
    in-out property <string> text: "";

    text := Text {
        visible: !root.editable;

        text: root.text;
    }
    LineEdit {
        visible: root.editable;

        text <=> root.text;
    }
}

export component TodoItem inherits HorizontalLayout {
    in-out property <string> text: "";
    in-out property <bool> done: false;
    property <bool> is_editing: false;

    callback done-changed;
    callback text-changed;

    spacing: 5px;

    CheckBox {
        checked <=> root.done;
        toggled => { root.done-changed() }
        horizontal-stretch: 0;
    }

    EditableLabel {
        editable: root.is_editing;
        text <=> root.text;
        horizontal-stretch: 1;
    }

    Button {
        text: root.is_editing ? "Done" : "Edit";
        clicked => {
            if (root.is_editing) {
                root.text-changed();
            }
            root.is_editing = !root.is_editing;
        }
        horizontal-stretch: 0;
    }
}
